version: 2

models:
  - name: first_click
    description: "First-click per order"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: first_click_source
        tests:
          - not_null

  - name: last_click
    description: "Last-click per order"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: last_click_source
        tests:
          - not_null
